export const HOSTNAMES = {
  CURSEFORGE: 'CURSEFORGE',
  WOWINTERFACE: 'WOWINTERFACE',
  GITHUB: 'GITHUB'
}

export const MIN_WINDOW_SIZE = { width: 850, height: 600 }

export const DL_PROGRESS = 'DL_PROGRESS'

// TODO: integrate channels dictionary to front/backends.
export const RENDERER_CHN = {
  ADDON_LIST: 'ADDON_LIST',
  MOD_ADDON_OBJ: 'MOD_ADDON_OBJ',
  UPDATE_ADDON_DL: 'UPDATE_ADDON_DL',
  ERROR: 'ERROR'
}

export const MAIN_CHN = {
  NEW_URL: 'NEW_URL',
  INSTALL_ADDON: 'INSTALL_ADDON',
  INSTALL_UPDATE: 'INSTALL_UPDATE',
  CHECK_ADDON_UPDATE: 'CHECK_ADDON_UPDATE',
  ERROR: 'ERROR',
  UNINSTALL_ADDON: 'UNINSTALL_ADDON',
  WINDOW_DONE_LOADING: 'WINDOW_DONE_LOADING'
}
