branches:
  only:
    - master
    - dev
    - feat-win-deploy
skip_tags: true
cache:
  - node_modules
environment:
  matrix:
    - nodejs_version: 8
install:
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Install-Product node $env:nodejs_version
  - ps: If ($env:APPVEYOR_REPO_BRANCH -eq "master") { $env:toggle_prerelease="false"; $env:rel_type="stable"} Else {$env:toggle_prerelease="true"; $env:rel_type="nightly"}
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
  - npm run build
matrix:
  fast_finish: true
build_script:
- cmd: npm run package-win
after_build:
- ps: 7z a WorldOfAddons-$env:package_version-$env:rel_type-win32x64.zip $env:APPVEYOR_BUILD_FOLDER\release
artifacts:
- path: release
  name: WorldOfAddons-$(package_version)-$(rel_type)-win32x64
shallow_clone: true
clone_depth: 1
deploy:
- provider: GitHub
  release: $(package_version)-$(rel_type)
  prerelease: $(toggle_prerelease)
  description: <i><b>[Please consult our wiki for installation and usage guides](https://github.com/WorldofAddons/worldofaddons/wiki)</b></i></br> Automatically built from branch `$(APPVEYOR_REPO_BRANCH)`, AppVeyor build `$(APPVEYOR_BUILD_VERSION)`</br></br>$(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: JPLPY6cHS8ydAPy2lc49ym1aBGk5uUStEAKfEQuVqdB2Jl9X/sfWdu4MVagLff1D
  artifact: WorldOfAddons-$(package_version)-$(rel_type)-win32x64.zip
  on:
    branch: $(APPVEYOR_REPO_BRANCH)
    